version: '3.9'

services:
  app:  # アプリケーション本体（FastAPIサーバー）のサービス定義
    build:
      context: .  # Dockerビルドのコンテキスト（プロジェクトルート）
      dockerfile: Dockerfile  # 使用するDockerfileのパス
    container_name: crud-sample-backend-app  # コンテナ名（任意指定）
    ports:
      - "8000:8000"  # ホスト:コンテナ間でポート8000をバインド（FastAPIのデフォルト）
    environment:
      - AWS_REGION=ap-northeast-1  # AWSリージョン（Cognito等で利用）
      - USER_POOL_ID=your_cognito_user_pool_id  # CognitoユーザープールID
      - APP_CLIENT_ID=your_cognito_app_client_id  # CognitoアプリクライアントID
    volumes:
      - ./src:/src  # ホストのカレントディレクトリをコンテナの/srcにマウント（ホットリロードや開発時に便利）
    command: python run uvicorn src.main:app --host 0.0.0.0 --port 8000

  test:  # テスト実行用サービス（CI/CDや開発時の自動テストに活用）
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-sample-backend-test  # テスト用コンテナ名
    environment:
      - AWS_REGION=ap-northeast-1
      - USER_POOL_ID=your_cognito_user_pool_id
      - APP_CLIENT_ID=your_cognito_app_client_id
    volumes:
      - ./src:/src  # ホストのカレントディレクトリをコンテナの/srcにマウント（ホットリロードや開発時に便利）
    command: sh -c "pip install pytest && pytest"
  # 起動時にpytestをインストールし、テストを実行
  # requirements.txtにpytestを含めたくない場合の運用例

  local:  # ローカル環境でのテストケース実行用
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-sample-backend-test  # テスト用コンテナ名
    environment:
      - AWS_REGION=ap-northeast-1
      - USER_POOL_ID=your_cognito_user_pool_id
      - APP_CLIENT_ID=your_cognito_app_client_id
    volumes:
      - ./src:/src  # ホストのカレントディレクトリをコンテナの/srcにマウント（ホットリロードや開発時に便利）
    command: sh -c "pip install pytest && pytest"
    # 起動時にpytestをインストールし、テストを実行
    # requirements.txtにpytestを含めたくない場合の運用例
